title: NaturHänsyn
author:
  name: Föreningen NaturHänsyn
  email: 'naturhansyn@gmail.com'
metadata:
  description: 'Föreningen NaturHänsyn arbetar för att skydda värdefull natur i Sverige genom bevakning, bestridande, folkbildning och påverkan.'
